package com.example.demo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;



@DynamoDBTable(tableName = "picture")
public class Pictures {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String picture_id;
	
	@DynamoDBAttribute
	private String property_id;
	
	@DynamoDBAttribute
	private String picutre_url;

	public Pictures(String picture_id, String property_id, String picutre_url) {
		super();
		this.picture_id = picture_id;
		this.property_id = property_id;
		this.picutre_url = picutre_url;
	}

	public String getPicture_id() {
		return picture_id;
	}

	public void setPicture_id(String picture_id) {
		this.picture_id = picture_id;
	}

	public String getProperty_id() {
		return property_id;
	}

	public void setProperty_id(String property_id) {
		this.property_id = property_id;
	}

	public String getPicutre_url() {
		return picutre_url;
	}

	public void setPicutre_url(String picutre_url) {
		this.picutre_url = picutre_url;
	}
	
	
	
}
