package com.example.demo.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "property")
public class property {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String property_id;
	
	@DynamoDBAttribute
	private Address address;
	
	@DynamoDBAttribute
	private String demand_amount;

	@DynamoDBAttribute
	private String dealer_id;
	
	public property(String property_id, Address address, String demand_amount, String dealer_id) {
		super();
		this.property_id = property_id;
		this.address = address;
		this.demand_amount = demand_amount;
		this.dealer_id = dealer_id;
	}

	public String getProperty_id() {
		return property_id;
	}

	public void setProperty_id(String property_id) {
		this.property_id = property_id;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getDemand_amount() {
		return demand_amount;
	}

	public void setDemand_amount(String demand_amount) {
		this.demand_amount = demand_amount;
	}

	public String getDealer_id() {
		return dealer_id;
	}

	public void setDealer_id(String dealer_id) {
		this.dealer_id = dealer_id;
	}
	


}
